feat: introduce `gluesql-logic-test` script (#10)
This pull request introduces a CLI tool, cargo run --bin gluesql-logic-test, to run sqllogictest testcases. With this, we now have feedback loop to complement GlueSQL more! This tool just runs with in-memory storage backend now, but the next PR may support other storage backends too (e.g., CSV, JSON, etc)

```
$ cargo run --bin gluesql-logic-test -- slt/random/expr
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/gluesql-logic-test slt/random/expr --verbose`
Found 120 test files
Running test: slt/random/expr/slt_good_0.test
✗ slt/random/expr/slt_good_0.test - Error: query result mismatch:
[SQL] SELECT 20 / - - 96 + CAST ( 90 AS INTEGER ) AS col2
[Diff] (-expected|+actual)
-   90
+   90.20833333333333
at slt/random/expr/slt_good_0.test:46

Error: query result mismatch:
[SQL] SELECT 20 / - - 96 + CAST ( 90 AS INTEGER ) AS col2
[Diff] (-expected|+actual)
-   90
+   90.20833333333333
at slt/random/expr/slt_good_0.test:46
```


* chore: bump dependencies

* feat: implement gluesql-logic-test

* fix: ignore trailing comments

* fix: ignore trailing comments when running single file too

* fix: infer result's types

* docs: complement README.md

* chore: remove unintended file

* fix: apply cargo-clippy suggestions

* refactor: remove duplicated logic

* chore: bump GlueSQL to HEAD

* fix: use value-wise style sql-result validator

* feat: provide `--fail-fast` option

* fix: correct regex

* chore: introduce helper Python script

* fix: apply cargo-clippy suggestions